version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '22:00'
      timezone: 'Europe/London'
    rebase-strategy: 'disabled'
